# Trading pairs
SYMBOLS = [
    "BTC/USDT",
    "ETH/USDT",
    "SOL/USDT"
]

# Market timeframe
TIMEFRAME = "1h"

# Bot refresh interval (seconds)
SCAN_INTERVAL = 60

# RSI settings
RSI_PERIOD = 14

RSI_BUY_THRESHOLD = 30
RSI_SELL_THRESHOLD = 70

# SMA settings
SMA_SHORT_WINDOW = 20
SMA_LONG_WINDOW = 50

CANDLE_LIMIT = 500
STOP_LOSS_PERCENT = 5
TAKE_PROFIT_PERCENT = 10
MACD_FAST_WINDOW = 12
MACD_SLOW_WINDOW = 26
MACD_SIGNAL_WINDOW = 9
BUY_POSITION_PERCENT = 30
STRONG_BUY_POSITION_PERCENT = 70